name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:
    branches:
      - master
      - staging
      - develop

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: api.timos.design
          username: root
          password: ${{ secrets.SERVER_PW }}
          script: |
            cd /root/GoFeed-Backend
            git stash
            git pull
            docker-compose build
            docker-compose up -d --remove-orphans
